name: Tests
on: [ push ]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:14
    services:
      mongo:
        image: mongo:5.0.3
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm ci
      - name: Tests
        run: npm test
        env:
          MONGO_HOST: mongo
